---
- name: Ensure Python requirements are met locally
  run_once: true
  become: false
  delegate_to: localhost
  pip:
    requirements: "{{ role_path }}/files/requirements.txt"

- name: Initialize golden-base facts
  set_fact: 
    existing_vms: false
    golden_ip: "unknown"
    # Create a timestamp for version tracking
    build_timestamp: "{{ lookup('pipe', 'date +%Y%m%d-%H%M') }}"

- name: Build Rocky Linux base image block
  block:
    - name: Run virt-install for golden-base
      import_tasks: 00_create_golden.yml
      delegate_to: "{{ VM_HOST_IP }}"
  
    - name: Wait for Auto-Install shutdown
      import_tasks: 01_wait_for_shutdown.yml
      delegate_to: "{{ VM_HOST_IP }}"

    - name: sysprep
      import_tasks: 02_sysprep.yml
      delegate_to: "{{ VM_HOST_IP }}"
  when: 
    - "'kvm' in group_names"