#!/bin/bash

# Default values
CHECKOUT="origin/main"
VENV_PATH="{$HOME}/deploy/venv"

# Parse options
while getopts "d:i:U:C:v:e:" opt; do
  case $opt in
    d) DEST_DIR="$OPTARG" ;;
    i) INVENTORY="$OPTARG" ;;
    U) REPO_URL="$OPTARG" ;;
    C) CHECKOUT="$OPTARG" ;;
    v) VENV_PATH="$OPTARG" ;;
    e) EXTRA_VARS="-e $OPTARG" ;;
    *) echo "Usage: ansible.execute -d dir -i inv -U url [-C checkout] [-v venv] [-e vars] playbook" && exit 1 ;;
  esac
done
shift $((OPTIND-1))

PLAYBOOK=$1

if [ -z "$PLAYBOOK" ]; then
    echo "Error: No playbook specified."
    exit 1
fi

# 1: Download/Sync only
ansible-pull -d "${DEST_DIR}" -U "${REPO_URL}" -C "${CHECKOUT}" --list-hosts 2>/dev/null


# 2: Move to destination
cd "${DEST_DIR}/ansible" || { echo "Failed to enter ${DEST_DIR}/ansible."; exit 1; }


# 3: Source environment
if [ -d "${VENV_PATH}" ]; then
    echo "--- Step 3: Sourcing environment: ${VENV_PATH} ---"
    source "${VENV_PATH}/env_build.sh"
fi
source "{{ playbook_dir }}/../temp.txt"

# Ensure ANSIBLE_CONFIG is set if not already passed in the SSH string
export ANSIBLE_CONFIG="${DEST_DIR}/ansible/ansible.cfg"
# pwd  && echo ${PLAYBOOK}
# 4: Run the actual playbook
echo "--- Step 4: Executing ansible-playbook ---"
ansible-playbook -i "${INVENTORY}" "${PLAYBOOK}" ${EXTRA_VARS}

env|grep ipa_