- name: Check if IPA package is actually installed
  ansible.builtin.shell: "rpm -q ipa-server"
  register: rpm_check
  failed_when: false
  changed_when: false

- name: Check for IPA configuration file
  become: yes
  ansible.builtin.stat:
    path: /etc/ipa/default.conf
  register: ipa_conf_file

- name: Check IPA service status
  become: yes
  ansible.builtin.command: "ipactl status"
  register: ipa_service_check
  failed_when: false
  changed_when: false

- name: see results
  debug:
    msg:
     - "ipa_service_check {{ ipa_service_check.stdout }}"
     - "ipa_conf_file {{ ipa_conf_file.stat.exists }}"
     - "rpm_check {{ rpm_check.rc }}"


- name: "Determine IPA Stage"
  ansible.builtin.set_fact:
    ipa_stage: "{{ item.stage }}"
  when: item.condition
  loop:
    # Use the return code from rpm -q (0 means it is installed)
    - stage: "required"
      condition: "{{ rpm_check.rc != 0 }}"
    
    # - stage: "installed"
    #   condition: "{{ rpm_check.rc == 0 and not ipa_conf_file.stat.exists }}"

    - stage: "unconfigured"
      condition: "{{ 'IPA is not configured' in ipa_service_check.stdout }}"
    
    - stage: "configured"
      condition: "{{ ipa_conf_file.stat.exists and 'IPA is not configured' not in ipa_service_check.stdout }}"
    
    - stage: "running"
      condition: "{{ ipa_conf_file.stat.exists and 'IPA is not configured' not in ipa_service_check.stdout }}"