- name: Check if IPA default.conf exists
  stat:
    path: /etc/ipa/default.conf
  register: ipa_conf

# --- Install only if not configured ---
- name: Configure IPA server on {{ ca_hostname }} (this can takes a while - 10 min+)
  become: yes
  environment:
    PKI_TIMEOUT: "600" # Increase timeout to 10 minutes
  ansible.builtin.shell: |
    umask 022 && ipa-server-install \
      --unattended \
      --domain={{ ipa_domain | lower }} \
      --realm={{ ipa_realm }} \
      --ds-password='{{ ipa_dm_password }}' \
      --admin-password='{{ ipa_admin_password }}' \
      --hostname={{ ca_hostname }} \
      --setup-dns \
      --auto-forwarders \
      --auto-reverse \
      --allow-zone-overlap \
      --no-host-dns
  register: ipa_install_out
  when: 
    - ipa_stage == 'unconfigured'
    - ipa_role | default('primary') == 'primary'
  no_log: true

- name: create certs from cacert.p12
  become: yes
  shell: |
    # Extract only the private key using legacy and skipping MAC verification
    openssl pkcs12 -in /root/cacert.p12 -nocerts -nodes -out /root/serverkey.pem -clcerts -passin pass:{{ ipa_dm_password }} -legacy -nomacver
    
    # Extract only the certificate using legacy and skipping MAC verification
    openssl pkcs12 -in /root/cacert.p12 -clcerts -nokeys -out /root/servercert.pem -passin pass:{{ ipa_dm_password }} -legacy -nomacver
  # no_log: true


- name: copy ca.crt to trusted
  become: yes
  shell: |
    cp /etc/ipa/ca.crt /etc/pki/ca-trust/source/anchors/
    update-ca-trust
