---
- name: Pin IPA Master Details
  set_fact:
    # Force the master to be the first host in the 'ipa' group
    ipa_master_fqdn: "{{ hostvars[groups['ipa'][0]]['hostname'] }}"
    ipa_master_ip: "{{ hostvars[groups['ipa'][0]]['ansible_host'] }}"
    controller_node: "{{ groups['ipa_helpers'][0] | default('helper') }}"
  run_once: true # Ensures this is calculated once and shared
      
- name: test our connections on {{ guest_member }}
  import_tasks: connections.yml
  
- name: Check IPA status
  import_tasks: check_status.yml
  
- name: Show check status
  debug:
    msg: 
      - "host {{ inventory_hostname }}"
      - "stage {{ipa_stage}}"
      - "type {{ipa_type}}"
      - "ipa_master_fqdn {{ipa_master_fqdn}}"
      - "ipa_master_ip {{ipa_master_ip}}"
      - "controller_node {{controller_node}}"

# - "ipa_continue {{ipa_continue | default( "not defined ")}}"
  
- name: Initial, Health & Recovery Self-healing
  block:
      # --- STAGE 1: Install RPMs & Prepare ---
      - name: Process Stage 1 - Installation
        import_tasks: install_ipa.yml
        when: 
          - ipa_stage == 'required'
          - ipa_continue is not defined

      - name: Dynamic Re-check
        ansible.builtin.include_tasks: check_status.yml
        when: ipa_install_result.changed | bool
      
      - name: What is check_status
        debug:
          msg: 
            - "ipa_install_result.changed {{ipa_install_result.changed | bool}}"
            - "host {{ inventory_hostname }}"
            - "stage {{ipa_stage}}"
            - "type {{ipa_type}}"
            - "ipa_master_fqdn {{ipa_master_fqdn}}"
            - "ipa_master_ip {{ipa_master_ip}}"
            - "controller_node {{controller_node}}"
      
      # --- STAGE 2: configrue the primary ---      
      - name: Process Stage 2 - Primary host Configuration
        no_log: true
        import_tasks: ipa_master.yml
        vars:
          ipa_domain: "{{ lookup('env', 'ipa_domain') |lower}}"
          ipa_realm:  "{{ lookup('env', 'ipa_domain') |upper}}"
          ipa_dm_password: "{{ lookup('env', 'ipa_dm_password')}}"
          ipa_admin_password: "{{ lookup('env', 'ipa_admin_password')}}"
          ipa_master: "{{ hostvars[inventory_hostname].hostname | default( lookup('env', 'ipa_master')) }}"
          ipa_master_ip: "{{ hostvars[inventory_hostname].ansible_host | default( lookup('env', 'ipa_master_ip'))}}"
          ca_hostname: "{{ hostvars[inventory_hostname].hostname | default( lookup('env', 'ipa_master'))}}"
          ipa_role: "{{ ipa_type }}"
        when: 
          - ipa_stage == 'unconfigured'
          - ipa_type in ('primary', 'master')

      - name: Dynamic Re-check
        include_tasks: check_status.yml
        when: ipa_install_result.changed | bool

      - name: What is check_status
        debug:
          msg: 
            - "ipa_install_result.changed {{ipa_install_result.changed | bool}}"
            - "host {{ inventory_hostname }}"
            - "stage {{ipa_stage}}"
            - "type {{ipa_type}}"
            - "ipa_master_fqdn {{ipa_master_fqdn}}"
            - "ipa_master_ip {{ipa_master_ip}}"
            - "controller_node {{controller_node}}"

      # --- Mid STAGE 2: verification Master Settings ---
      - name: Verify connection 
        import_tasks: ipa_service_check.yml
        no_log: true
        vars:
          ipa_admin_password: "{{ lookup('env', 'ipa_admin_password')}}"
          search_domain: "{{ lookup('env', 'ipa_domain') |lower}}"
          nameserver_ip: "{{ ipa_master_ip }} "
          ipa_master_fqdb: "{{ hostvars[groups['ipa'][0]]['hostname'] }}"
          next_host: "{{ hostvars[groups['ipa'][1]]['ansible_host'] }}"
        when: 
          - ipa_stage == 'running'
          - ipa_type in ('primary', 'master')

      - name:  Process Stage 3 - replica host Configuration
        import_tasks: ipa_replica.yml
        vars:
          ipa_master: "{{ hostvars[ipa_master_host]['inventory_hostname'] }}"
          ipa_master_ip: "{{ hostvars[ipa_master_host]['ansible_host'] }}"
          ipa_primary_fqdn: "{{ hostvars[ipa_master_host]['hostname'] }}"
          ipa_domain: "{{ lookup('env', 'ipa_domain') |lower}}"
          nameserver_ip: "{{ ipa_master_ip }} "
          ipa_master_fqdb: "{{ hostvars[groups['ipa'][0]]['hostname'] }}"
          ipa_admin_password: "{{ lookup('env', 'ipa_admin_password')}}"
        when: 
          - ipa_stage == 'unconfigured'
          - ipa_type in ('replica')
          - "'helpers' not in groups"

      # --- Inside ipa_replica.yml ---

      - name: Final Service Validation (replica)
        import_tasks: ipa_service_check.yml
        vars:
          ipa_admin_password: "{{ lookup('env', 'ipa_admin_password') }}"
          search_domain: "{{ lookup('env', 'ipa_domain') | lower }}"
          # We want to test the Secondary's IP
          nameserver_ip: "{{ ansible_host }}" 
          # The physical node performing the test
          next_host: "{{ hostvars[groups['helpers'][0]]['ansible_host'] }}"
        when: 
          - ipa_stage == 'running'
          - ipa_type == 'replica'
          - "'helpers' not in groups"

      - name:  Process Stage 4 - replica host Configuration (helper)
        import_tasks: ipa_replica.yml
        vars:
          ipa_master: "{{ hostvars[ipa_master_host]['inventory_hostname'] }}"
          ipa_master_ip: "{{ hostvars[ipa_master_host]['ansible_host'] }}"
          ipa_primary_fqdn: "{{ hostvars[ipa_master_host]['hostname'] }}"
          ipa_domain: "{{ lookup('env', 'ipa_domain') |lower}}"
          nameserver_ip: "{{ ipa_master_ip }} "
          ipa_master_fqdb: "{{ hostvars[groups['ipa'][0]]['hostname'] }}"
          ipa_admin_password: "{{ lookup('env', 'ipa_admin_password')}}"
        when: 
          - ipa_stage == 'unconfigured'
          - ipa_type in ('replica')
          - "'helpers' in groups"

      # --- Inside ipa_replica.yml ---

      - name: Final Service Validation (helper)
        import_tasks: ipa_service_check.yml
        vars:
          ipa_admin_password: "{{ lookup('env', 'ipa_admin_password') }}"
          search_domain: "{{ lookup('env', 'ipa_domain') | lower }}"
          # We want to test the Secondary's IP
          nameserver_ip: "{{ ansible_host }}" 
          # The physical node performing the test
          next_host: "{{ hostvars[groups['ipa'][1]]['ansible_host'] }}"
        when: 
          - ipa_stage == 'running'
          - ipa_type == 'replica'

  when: ipa_type in ['primary', 'master', 'member', 'replica']