---
- name: Pin IPA Master Details
  set_fact:
    # Force the master to be the first host in the 'ipa' group
    ipa_master_fqdn: "{{ hostvars[groups['ipa'][0]]['hostname'] }}"
    ipa_master_ip: "{{ hostvars[groups['ipa'][0]]['ansible_host'] }}"
    controller_node: "{{ groups['ipa_helpers'][0] | default('helper') }}"
  run_once: true # Ensures this is calculated once and shared
      
- name: test our connections on {{ guest_member }}
  import_tasks: connections.yml
  
- name: Check IPA status
  import_tasks: check_status.yml
  
- name: What is check_status
  debug:
    msg: 
      - "host {{ inventory_hostname }}"
      - "stage {{ipa_stage}}"
      - "type {{ipa_type}}"
      - "ipa_master_fqdn {{ipa_master_fqdn}}"
      - "ipa_master_ip {{ipa_master_ip}}"
      - "controller_node {{controller_node}}"

# - "ipa_continue {{ipa_continue | default( "not defined ")}}"
  
- name: Initial, Health & Recovery Self-healing
  block:

  # --- STAGE 1: Install RPMs & Prepare ---
  - name: Process Stage 1 - Installation
    import_tasks: install_ipa.yml
    when: 
      - ipa_stage == 'required'
      - ipa_continue is not defined

  - name: Dynamic Re-check
    ansible.builtin.include_tasks: check_status.yml
    when: ipa_install_result.changed | bool

  - name: What is check_status
    debug:
      msg: |
        - "host {{ inventory_hostname }}"
        - "stage {{ipa_stage}}"
        - "type {{ipa_type}}"
        - "ipa_master_fqdn {{ipa_master_fqdn}}"
        - "ipa_master_ip {{ipa_master_ip}}"
        - "controller_node {{controller_node}}"
        - "ipa_continue {{ipa_continue}}"

  - name: Process Stage 2 - Primary host Configuration
    import_tasks: ipa_master.yml
    vars:
      ipa_domain: "{{ lookup('env', 'ipa_domain') |lower}}"
      ipa_realm:  "{{ lookup('env', 'ipa_domain') |upper}}"
      ipa_dm_password: "{{ lookup('env', 'ipa_dm_password')}}"
      ipa_admin_password: "{{ lookup('env', 'ipa_admin_password')}}"
      ipa_master: "{{ hostvars[inventory_hostname].hostname | default( lookup('env', 'ipa_master')) }}"
      ipa_master_ip: "{{ hostvars[inventory_hostname].ansible_host | default( lookup('env', 'ipa_master_ip'))}}"
      ca_hostname: "{{ hostvars[inventory_hostname].hostname | default( lookup('env', 'ipa_master'))}}"
      ipa_role: "{{ ipa_type }}"
    when: 
      - ipa_stage == 'unconfigured'
      - ipa_type in ('primary', 'master','replica')


  #   # --- STAGE 3 & 4: Self-Healing & Maintenance ---
  #   - name: Self-healing - Ensure Services are Running
  #     ansible.builtin.command: ipactl start
  #     when: 
  #       - ipa_stage in ['configured', 'running']
  #       - ipa_service_check.rc != 0
  #     register: repair_attempt

  #   - name: Weekly Maintenance - Sync CA Trust & DNS
  #     block:
  #       - name: Force CA Trust Sync
  #         ansible.builtin.shell: |
  #           cp /etc/ipa/ca.crt /etc/pki/ca-trust/source/anchors/
  #           update-ca-trust
  #         changed_when: false

  #       - name: Re-verify Infrastructure DNS Records
  #         ansible.builtin.command: >
  #           ipa dnsrecord-add {{ ipa_domain }} {{ item.name }} --a-rec={{ item.ip }}
  #         loop:
  #           - { name: "{{ ipa_master }}", ip: "{{ ipa_master_ip }}" }
  #           - { name: "{{ ipa_helper }}", ip: "{{ ipa_helper_ip }}" }
  #         register: dns_sync
  #         failed_when: false
  #         changed_when: "'added' in dns_sync.stdout"
  #     when: ipa_stage == "running" or (repair_attempt is defined and repair_attempt.rc == 0)

  # Global Gate: Don't run on helpers or unknown types
  when: ipa_type in ['primary', 'master', 'member', 'replica']