- name: Initialize guest configuration map
  set_fact:
    guest_configs: {}
    golden_image_raw: none
    skip_config: true

- name: determine which image to clone.
  import_tasks: 01_determine_os_identity.yml

- name: Annouce the deployment type
  debug:
    msg: "{{ guest_member }} is being cloned from {{ guest_configs[guest_member] }}"

- name: Update Build Profile
  set_fact: 
    build_profile: "{{ guest_configs[guest_member].profile }}"
    
- name: Cloning guest hosts
  import_tasks: 02_clone_to_guest.yml

- name: check if the image is already "Sealed"
  vars:
    nat_seg: "{{ net_maintenance }}"
    pro_seg: "{{ net_provider }}"
    cld_seg: "{{ net_provision }}"
  include_tasks: pre_clone.yml

- name: Run Guest Configuration
  include_tasks: 03_Config_guest.yml
  # Only run if the node is NOT reachable OR we explicitly requested a reclone
  when: not skip_config | bool

# - name: Update Member network connectivity
#   import_tasks: 03_Config_guest.yml
- name: post initialise fips
  vars:
    pro_seg: "{{ net_provider }}"
  include_tasks: post_clone.yml
  when: guest_member in groups['helpers']

- name: "Storage - Cleanup Orphaned Golden Images"
  ansible.builtin.shell: |
    # 1. Identify GI names
    GI_NAMES=$(virsh list --all --name | grep "^gi-" | grep -v "20260425"| sed 's/[[:space:]]//g'| tr -d "\n")
    
    # 2. Capture XML from all running VMs into one searchable blob
    # We use '|| true' to prevent failure if no VMs are running
    PROTECTOR_XML=$(virsh list --name | grep . | xargs -I {} virsh dumpxml {} 2>/dev/null || true)
    
    # 3. Process the cleanup
    echo "$GI_NAMES" | while read -r gi; do
        [ -z "$gi" ] && continue
        
        if echo "$PROTECTOR_XML" | grep -q "$gi"; then
            # Found a reference - keep it safe
            echo "KEEPING: $gi is in use by a running node."
            : 
        else
            # No reference found - execute deletion
            echo "DELETING: $gi is orphaned."
            virsh undefine "$gi" --nvram || true
            rm -f "/var/lib/libvirt/images/$gi.qcow2"
        fi
    done
  register: cleanup_output
  changed_when: "'DELETING' in cleanup_output.stdout"