cloud_helper_workdir: "{{ lookup('env','cloud_helper_workdir') | default('/opt/cloud-helper', true) }}"
output_dir: "{{ cloud_helper_workdir }}/ignition"
disk_size: "10G"
kubernetes_version: "{{ lookup('env','kubetnet_version') | default('1.34', true) }}"
crio_version: "{{ lookup('env','kubetnet_version') | default('1.34', true) }}"
crio_stream: "stable"
cloud_helper_shell: "/bin/bash"
iso_path: "{{ lookup('env','iso_path') | default('/var/lib/libvirt/image/Rocky-9-latest-x86_64-dvd.iso', true) }}"
build_loops: "{{ bl|default(120)}}"
tpwd_hash: "{{ lookup('env','admin_hash') }}"
tsecops_hash: "{{ lookup('env','secops_hash') }}"
tsecops_key: "{{ lookup('env','secops_key') }}"
mycrio_config: |
  [crio.runtime]
  conmon = "/usr/bin/conmon"
  log_level = "info"
  pids_limit = 2048

mykubelet_config: |
  kind: KubeletConfiguration
  apiVersion: kubelet.config.k8s.io/v1beta1
  address: "0.0.0.0"
  cgroupDriver: "systemd"

# Use the env var if provided, otherwise you can leave it empty to force an error 
# or provide a default for testing.
cluster_token: "{{ lookup('env', 'K8S_CLUSTER_TOKEN') | default('abcdef.1234567890abcdef', true) }}"
# DNS Zone Defaults - Prioritize Environment Variables
ipa_master_fqdn: "{{ lookup('env', 'ipa_master') | default('ipa01.home.morinsoft.ca', true) }}"
ipa_admin_password: "{{ lookup('env','ipa_admin_password')}}"
c_zone: "{{ lookup('env', 'cloud_zone') | default('cloud.home.morinsoft.ca', true) }}"
p_zone: "{{ lookup('env', 'cloud_provision') | default('provision.home.morinsoft.ca', true) }}"
# Kubernetes API Virtual IP
k8s_api_vip: "{{ lookup('env', 'k8s_api_vip') | default('192.168.100.30', true) }}"
vip_interface: "enp1s0"

# Network Lookups from Inventory
# We fetch the CIDRs once here so they are available globally in the role
cloud_cidr: "{{ hostvars['kvmdc01'].libvirt_networks | selectattr('name', 'equalto', 'default') | map(attribute='cidr') | first | default('192.168.100.0/24') }}"
prov_cidr: "{{ hostvars['kvmdc01'].libvirt_networks | selectattr('name', 'equalto', 'br-cluster') | map(attribute='cidr') | first | default('10.0.0.0/24') }}"

# Dynamic Reverse Zone Calculation
rev_cloud: "{{ cloud_cidr | ansible.utils.ipaddr('revdns') | regex_replace('^0\\.', '') }}"
rev_prov: "{{ prov_cidr | ansible.utils.ipaddr('revdns') | regex_replace('^0\\.', '') }}"
