---
- name: "Deployment Guard: Block Managed Infrastructure"
  hosts: localhost
  connection: local
  gather_facts: false # We don't need facts if we are using shell
  tasks:
    - name: "Check if local hostname exists in the inventory file"
      ansible.builtin.shell: |
        grep -cw "$(hostname -s)" /home/core/deploy/inventory.yml
      register: host_check
      changed_when: false

    - name: "Validate Safety"
      ansible.builtin.fail:
        msg: |>

          --------------------------------------------------------------------------
          SAFETY TRIGGERED: The hostname was found in the inventory.
          Execution is blocked on managed infrastructure servers.
          Execution of this script is not allowed on infra or cloud systems.
          --------------------------------------------------------------------------
      when: host_check.stdout | int > 0
# 1. Prepare Environment
- name: load environment
  hosts: all
  gather_facts: false
  tasks:
    - name: Ensure latest stable collections are installed on controller
      delegate_to: localhost
      become: false
      run_once: true
      command: "ansible-galaxy collection install {{ item }} --upgrade"
      loop:
        - community.general
        - ansible.posix
        - kubernetes.core  # Highly recommended for your FCOS/K8s work
      changed_when: false # These commands check for updates every time

- name: Build Golden Images
  vars:
    BUILD_PROFILE: "infra"
  hosts: kvm
  gather_facts: false
  roles:
    - role: rocky_infra_golden
# 1. Prepare Environment
- name: Build Kubernet Images
  vars:
    BUILD_PROFILE: "k8s"
  hosts: kvm
  gather_facts: false
  roles:
    - role: rocky_infra_golden

- name: KVM Image Factory - Clone Infrastructure & Helpers
  hosts: kvm
  become: true
  gather_facts: true
  vars:
    # Combine groups and ensure we don't process a host twice if it's in both
    target_guests: "{{ (groups['ipa_servers'] + groups['helpers']) | unique }}"
  tasks:
    - name: Trigger Cloning Role for each target guest
      include_role:
        name: rocky_server_deploy
      loop: "{{ target_guests }}"
      loop_control:
        loop_var: guest_member

- name: Pre Helper as new controller
  hosts: kvm
  gather_facts: false
  vars:
    # Combine groups and ensure we don't process a host twice if it's in both
    target_guests: "{{ (groups['ipa_servers'] + groups['helpers']) | unique }}"
  roles:
    - role: rocky_helper_prep
  
#internal_cluster_ips: "{{ (groups['ipa_servers'] | difference(groups['helpers'])) | map('extract', hostvars, ['provision_ip']) | list }}"

# - name: Build Golden Base Image
#   hosts: kvm
#   gather_facts: false
#   vars:
#     golden_image_name: "{{ lookup('env', 'golden_image_name') | default('golden-base', true) }}"
#     VM_HOST_IP: "{{ lookup('env', 'VM_HOST_IP') }}"
  
#   pre_tasks:
#     - name: Check if Golden Base already exists
#       delegate_to: "{{ VM_HOST_IP }}"
#       shell: "sudo virsh list --all | grep -qw '{{ golden_image_name }}' && echo 'YES' || echo 'NO'"
#       register: base_check
#       changed_when: false
#       run_once: true

#     - name: Set Build Flag
#       set_fact:
#         should_build_base: "{{ (base_check.stdout | trim == 'NO') or (force_new_image | default(false) | bool) or (new_image | default(false) | bool) }}"
#       run_once: true
#   tasks:
#     - name: Run Golden Image Build Role
#       include_role:
#         name: rocky_k8s_golden
#       when: should_build_base | bool

# # 4. Deploy Infrastructure (LBs and Base Config)
# - name: Deploy Cluster Infrastructure
#   hosts: kvm
#   gather_facts: false
#   roles:
#     - role: rocky_k8s_lbs
#     # You can uncomment and add rocky_k8s_base here if needed

# # 4. Deploy Infrastructure (LBs and Base Config)
# - name: Deploy Cluster nodes
#   hosts: kvm
#   gather_facts: false
#   roles:
#     - role: rocky_k8s_nodes