---
- name: "Bootstrap Controller and Check Network"
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: "Check if IPA Master DNS is reachable (Internal Network Check)"
      ansible.builtin.wait_for:
        host: "{{ hostvars[groups['ipa'][0]]['ansible_host'] }}"
        port: 53
        timeout: 2
      register: internal_dns_check
      ignore_errors: yes

    - name: Ensure latest stable collections are installed on controller
      community.general.ansible_galaxy_install:
        type: collection  # <--- Added this required argument
        name: "{{ item }}"
        upgrade: yes
      loop:
        - community.general
        - ansible.posix
        - kubernetes.core
      # If port 53 timed out (failed), it means ipa01 isn't restricting us yet.
      # So we are free to hit the internet for updates.
      when: internal_dns_check.failed
      ignore_errors: yes

- name: Configure IPA Infrastructure
  hosts: ipa_servers:helpers
  gather_facts: true
  serial: 1
  roles:
    - role: rocky_ipa
  

  