# 1. Prepare Environment
- name: load environment
  hosts: all
  gather_facts: false
  tasks:
    - name: Ensure latest stable collections are installed on controller
      delegate_to: localhost
      become: false
      run_once: true
      command: "ansible-galaxy collection install {{ item }} --upgrade"
      loop:
        - community.general
        - ansible.posix
        - kubernetes.core  # Highly recommended for your FCOS/K8s work
      changed_when: false # These commands check for updates every time

# 1. Prepare Environment
- name: load environment
  hosts: all
  gather_facts: false
  tasks:
    - name: Ensure latest stable collections are installed on controller
      delegate_to: localhost
      become: false
      run_once: true
      command: "ansible-galaxy collection install {{ item }} --upgrade"
      loop:
        - community.general
        - ansible.posix
        - kubernetes.core  # Highly recommended for your FCOS/K8s work
      changed_when: false # These commands check for updates every time

- name: Deploy IPA Servers
  include_role:
    name: rocky_ipa
  vars:
    # Pass the current loop item as the target for the role's tasks
    ansible_host: "{{ hostvars[guest_member]['ansible_host'] }}"
  loop: "{{ groups['ipa_servers'] }}"
  loop_control:
    loop_var: guest_member