---
- name: "Deployment Guard: Block Managed Infrastructure"
  hosts: localhost
  connection: local
  gather_facts: false 
  tasks:
    - name: "Validate Safety"
      debug:
        msg:
          - "--------------------------------------------------------------------------"
          - "SAFETY TRIGGERED: The hostname '{{ lookup('pipe', 'hostname -s') }}' was found in the inventory."
          - "Execution is blocked on managed infrastructure servers."
          - "--------------------------------------------------------------------------"
      # This checks if our actual short hostname is a member of the 'all' group
      when: lookup('pipe', 'hostname -s') in groups['all']

    - name: "Validate Safety"
      debug:
        msg:
          - "--------------------------------------------------------------------------"
          - "SAFETY TRIGGERED: The hostname was found in the inventory."
          - "Execution is blocked on managed infrastructure servers."
          - "Execution of this script is not allowed on infra or cloud systems."
          - "-------------------------------------------------------------------------"
      when: lookup('pipe', 'hostname -s') in groups['all']

    - name: "Terminate Execution"
      ansible.builtin.fail:
        msg: "Deployment halted for safety."
      when: lookup('pipe', 'hostname -s') in groups['all']

# 1. Prepare Environment
- name: load environment
  hosts: all
  gather_facts: false
  tasks:
    - name: Ensure latest stable collections are installed on controller
      delegate_to: localhost
      become: false
      run_once: true
      command: "ansible-galaxy collection install {{ item }} --upgrade"
      loop:
        - community.general
        - ansible.posix
        - kubernetes.core  # Highly recommended for your FCOS/K8s work
      changed_when: false # These commands check for updates every time

- name: Build Golden Images
  vars:
    BUILD_PROFILE: "infra"
  hosts: kvm
  gather_facts: false
  roles:
    - role: rocky_infra_golden
# 1. Prepare Environment
- name: Build Kubernet Images
  vars:
    BUILD_PROFILE: "k8s"
  hosts: kvm
  gather_facts: false
  roles:
    - role: rocky_infra_golden

- name: KVM Image Factory - Clone Infrastructure & Helpers
  hosts: kvm
  become: true
  gather_facts: true
  vars:
    # Combine groups and ensure we don't process a host twice if it's in both
    target_guests: "{{ (groups['ipa_servers'] + groups['helpers']) | unique }}"
  tasks:
    - name: Trigger Cloning Role for each target guest
      include_role:
        name: rocky_server_deploy
      loop: "{{ target_guests }}"
      loop_control:
        loop_var: guest_member

- name: Pre Helper as new controller
  hosts: kvm
  gather_facts: false
  vars:
    # Combine groups and ensure we don't process a host twice if it's in both
    target_guests: "{{ (groups['ipa_servers'] + groups['helpers']) | unique }}"
  roles:
    - role: rocky_helper_prep
  
- name: "Infra Stage setup Base"
  hosts: localhost
  connection: local
  gather_facts: False
  tasks:
    - name: "Verification Summary Results (Infrastructure Stage - Ambassador Model)"
      vars:
        ipa_realm: "{{ lookup('env', 'ipa_domain') | default('example.lan', true) | upper }}"
      ansible.builtin.debug:
        msg: 
          - "Golden Images: Base Immutable-ish OS base for infrastructure and cloud. ✔"
          - "Role Type: Infrastructure Identity & Directory Foundation. ✔"
          - "Primary Nodes: IPA01 (Master) and IPA02 (High-Availability Replica). ✔"
          - "Ambassador Node: Helper (Specialized Replica bridging Infra and Cloud). ✔"
          - "Security Compliance: FIPS-compliant kernel and CIS Level 2 Hardening enforced. ✔"
          - ""
          - "Next stage run the config_infra.yml playbook."
