---
- name: Get VM status from virsh list
  become: yes
  become_user: "{{ cloud_helper_user }}"
  shell: |
    if sudo virsh list --all | sed 's/shut off/shutdown/' | grep -q '{{ vm_host }}'; then
      sudo virsh list --all | sed 's/shut off/shutdown/' | awk '/{{ vm_host }}/ { if ($NF != "-") print $NF; else print "undefined" }'
    else
      echo "undefined"
    fi
  register: vm_status
  changed_when: false

- name: show status
  debug:
    msg: "golden-base state is {{ vm_status.stdout }} or {{ vm_status.stderr }}"

- name: Set fact for existing VMs
  set_fact:
    existing_vms: true
  when: "'undefined' not in (vm_status.stdout | trim)"

- debug:
    msg: "existing_vms missing"
  when: 
      - not existing_vms
  
- name: set ip_addr
  set_fact:
    ip_addr: "{{ ansible_host.split('.')[:3] | join('.') }}.30 }}"
  when: ansible_host is defined and ansible_host|length > 0

- name: set defauts ip info
  set_fact:
    ip_addr: "{{ ansible_host.split('.')[:3] | join('.') }}.30 }}"
    ip_mask: "{{ default_netmask }}"
    ip_gate: "{{ ansible_host.split('.')[:3] | join('.') }}.1"
    net_device: "{{ default_net_device }}"
  when: ansible_host is defined

- name: Validate required extra_vars
  assert:
    that:
      - ip_addr is defined
      - ip_mask is defined
      - net_device is defined
      - ip_gate is defined
    fail_msg: "Missing required extra_vars: ip_dns,ip_addr, ip_mask, net_device, ip_gate"

- name: Set default DNS if not defined
  set_fact:
    ip_dns: "{{ ip_dns | default( lookup('env','VM_HOST_IP').split('.')[:3] | join('.') ~ '.1' , true ) }}"

- name: Convert CIDR to subnet mask
  vars:
    cidr: 24
  set_fact:
    ip_mask: >-
      {{
        [ (['1'] * cidr + ['0'] * (32 - cidr))
          | join('')
          | regex_replace('(.{8})', '\\1 ')
          | split()
          | map('int', 2)
          | join('.')
      }}
  when: ip_cid is defined

- name: Calculate CIDR from subnet mask
  set_fact:
    ip_cid: >-
      {{
        ip_mask.split('.') |
        map('int') |
        map('regex_replace', '255', '8') |
        map('regex_replace', '254', '7') |
        map('regex_replace', '252', '6') |
        map('regex_replace', '248', '5') |
        map('regex_replace', '240', '4') |
        map('regex_replace', '224', '3') |
        map('regex_replace', '192', '2') |
        map('regex_replace', '128', '1') |
        map('regex_replace', '0', '0') |
        map('int') |
        sum
      }}

- name: get default cloud_helper keys
  become: true
  become_user: "{{ cloud_helper_user }}"
  set_fact:
    helper_ssh_key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
- debug:
    msg: "helper_ssh_key is {{ helper_ssh_key }}"
 
- debug:  
    msg: "cloud_helper_user is {{ cloud_helper_user }}"

- name: get local os version id
  delegate_to: localhost
  become: false
  shell: |
    cat /etc/os-release|grep VERSION_ID|sed 's/"//g' |awk -F= '{print $NF}'
  register: local_os_id

- name: get local os  id
  delegate_to: localhost
  become: false
  shell: |
    cat /etc/os-release|grep ^ID=|sed 's/"//g' |awk -F= '{print $NF}'
  register: local_os_name
  
- name: set vm variables
  set_fact:
    tdisk_size: 50
    tcpu_count: 2
    tram_size: 4096
    tvg_name: "vg_{{ vm_host }}"
    tvg_short: "{{ vm_host }}"
    tos_variant: "{{  local_os_id.stdout | default('9.7') }}"
    tos_name: "{{  local_os_name.stdout | default('rocky') }}"  

- name: Generate Kickstart files for new or forced VMs
  # become: true
  template:
    src: "golden.ks.j2"
    dest: "/home/{{ cloud_helper_user }}/{{ vm_host }}.ks"
    force: true
  when: 
    - not existing_vms
    - "'kvm' in group_names"
  vars:
    hostname: "{{ vm_host }}.{{ cloud_zone | default(ansible_domain) }}"
    disk_size: "{{ tdisk_size }}"
    vcpu_count: "{{ tcpu_count }}" 
    ram_size: "{{ tram_size }}"
    vg_name:  "{{ tvg_name }}"  
    vg_short: "{{ tvg_short }}"
    secops_hash: "{{ tsecops_hash }}"
    pwd_hash: "{{ tpwd_hash }}"
    ipa_host: "{{ vm_fqdn }}"
    ip_address: "{{ ansible_host }}"
    gateway: "{{ ip_gate }}"
    dns: "{{ ip_dns }}"
    net_device: "{{ net_device }}"
    ip_mask: "{{ ip_mask }}"
    ip_cid: "{{ ip_cid }}"
    crio_repo_ver: "{{ crio_version }}"
    kubernetes_repo_ver: "{{ kubernetes_version }}"
    core_ssh_key: "{{ helper_ssh_key }}"
    install_disk: "sda"
    dns_01: "8.8.8.8"
    dns_02: "{{ ip_gate }}"
    mycluster_ip_addr: "{{ cluster_ip_addr.split('.')[:3] | join('.') }}.{{ ansible_host.split('.')[-1] }}"
    cloud_master_ip: "{{ hostvars[groups['control_nodes'][0]].ansible_host }}"
    cluster_netmask: "{{ lookup('env', 'cluster_netmask') }}"
    cluster_gateway: "{{ lookup('env', 'cluster_gateway') }}"
    default_netmask: "{{ lookup('env', 'default_netmask') }}"
    default_net_device: "{{ lookup('env', 'default_net_device') }}"
    cluster_net_device: "{{ lookup('env', 'cluster_net_device') }}"
    nat_net_device: "{{ lookup('env', 'nat_net_device') }}"
    nat_mac_device: "{{ lookup('env', 'nat_mac_device') }}"
    my_controller_ip: "{{ controller_ip }}"
    my_os_variant: "{{ tos_variant }}"
  # no_log: true

- name: Execute virt-install non-interactively and wait for completion
  when: 
    - not existing_vms
    - "'kvm' in group_names"
  become: true
  command: >
    virt-install
      --name {{ vm_host }}
      --ram {{ tram_size }}
      --vcpus {{ tcpu_count }}
      --initrd-inject="/home/{{ cloud_helper_user }}/{{ vm_host }}.ks"
      --extra-args="inst.ks=file:/{{ vm_host }}.ks console=ttyS0,115200n8"
      --disk path=/var/lib/libvirt/images/{{ vm_host }}.qcow2,size={{ tdisk_size }},bus=sata
      --os-variant {{ tos_name}}{{ tos_variant.split('.')[0] }}
      {{ '--network network=br-nat,mac=' ~ nat_mac_device if nat_mac_device is defined else '--network network=br-nat' }}
      --network network=br-cluster
      {{ '--network network=default' if 'control_nodes' in group_names else '' }}
      {{ '--network network=default' if 'kvm' in group_names else '' }}
      --graphics none
      --console pty,target_type=serial
      --location {{ iso_path }}
      --noautoconsole
