# ──────── STAGE: Build if needed ─────────
- name: Get current epoch time from localhost
  become: false
  shell: date +%s
  register: epoch_result
  delegate_to: localhost
  changed_when: false

- name: Set global epoch fact
  set_fact:
    global_epoch: "{{ epoch_result.stdout | int }}"
    vm_host: "{{ inventory_hostname_short }}"
  when: "'kvm' not in group_names"

- name: Set global epoch fact
  set_fact:
    global_epoch: "{{ epoch_result.stdout | int }}"
    vm_host: "golden-base"
  when: "'kvm' in group_names"

- name: Set VM shutdown poll start time
  set_fact:
    vm_shutdown_start: "{{ global_epoch }}"

# - name: Trigger build if needed
#   include_tasks: define_vms.yml
  # when: vm_stage_map[vm_host] in ['build', 'building']

- name: Calculate wait time in minutes
  set_fact:
    wait_time_to_shutdown_or_fail: "{{ ((build_loops | int) * 10 // 60) }}"

- name: Display wait time
  debug:
    msg: "Probe VM will wait up to {{ wait_time_to_shutdown_or_fail }} minutes before resuming to next tasks"

- name: Probe VM with virsh until VM powers down
  shell: |
    sudo virsh list --all | sed 's/shut off/shutdown/' | grep -i "^.*{{ vm_host }}.*" | awk '{print $NF}'
  register: vm_state
  delegate_to: "{{ VM_HOST_IP }}"
  failed_when: false
  changed_when: false
  until: vm_state.stdout_lines[-1] == "shutdown"
  retries: "{{ build_loops|int }}"
  delay: 10

