
- name: Wait for SSH on golden-base 
  wait_for: 
    timeout: 15

- name: Start golden-base VM
  shell: sudo virsh start golden-base
  delegate_to: "{{ VM_HOST_IP }}"

- name: Wait for golden-base VM to be running
  shell: |
    sudo virsh list --all | grep golden-base | awk '{print $NF}'
  register: vm_state
  delegate_to: "{{ VM_HOST_IP }}"
  failed_when: false
  changed_when: false
  until: vm_state.stdout == "running"
  retries: "{{ build_loops | int }}"
  delay: 10

- name: Get golden-base VM IP
  shell: |
    sudo virsh net-dhcp-leases br-nat | \
    grep $(sudo virsh domiflist golden-base | grep br-nat | awk '{print $NF}') | \
    awk -F/ '{print $1}' | awk '{print $NF}'
  register: gold_ip
  delegate_to: "{{ VM_HOST_IP }}"

- name: wait 20 seconds
  shell: sleep 20
  delegate_to: localhost

- set_fact:
    golden_ip: "{{ gold_ip.stdout }}"


- name: Probe ssh until service is ready on golden-base
  delegate_to: localhost
  become: false
  shell: |
    ssh core@"{{ golden_ip }}" -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null echo sshok
  register: ssh_check
  failed_when: false
  changed_when: false
  until: ssh_check.stdout == "sshok"
  retries: "{{ build_loops | int }}"
  delay: 10

- name: Mark golden-base as ready
  set_fact:
    golden_ready: true