# role/ipa_setup/defaults/main.yml
ipa_stat: "initial"
ipa_type: "{{ hostvars[inventory_hostname]['cluster_role'] | default('client') }}"
is_ipa_pkg: False
ipa_role: master         # Options: master, replica
ipa_hostname: "{{ ansible_fqdn }}"
ipa_setup_dns: true
ipa_setup_ca: true       # Set false for replica unless promoting CA
ipa_mkhomedir: true
ipa_no_forwarders: true
ipa_no_ntp: true
ipa_no_hbac_allow: true
ipa_dns_zones:
  - name: "{{ lookup('env', 'ipa_domain') | lower }}"
    allow_transfer: "{{ groups['ipa_servers'] | map('extract', hostvars, ['ansible_host']) | list }}"
    allow_query:
      - "any"
    allow_update: "{{ groups['ipa_servers'] | map('extract', hostvars, ['ansible_host']) | list }}"

ipa_ca_intermediate: "{{ groups['ca_intermediate'][0] }}"
ipa_ca_intermediate_ip: "{{ hostvars[groups['ca_intermediate'][0]].ansible_host }}"
ipa_helper: "{{ groups['helpers'][0] }}"
ipa_helper_ip: "{{ hostvars[groups['helpers'][0]].ansible_host }}"
